### GET All
GET https://follow-service.onrender.com/api/ranking HTTP/1.1

### PUT Word
PUT https://follow-service.onrender.com/api/ranking/one HTTP/1.1

### GET Cache Clear
GET https://follow-service.onrender.com/api/cacheclear HTTP/1.1
